name: continuous integration example

on:
  push:
    branches:
      main

jobs:
  build-and-test-please:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Build with gradle!
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Run tests!
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew test

  system-test:
    runs-on: ubuntu-latest
    needs: builds-and-test-please

    steps:
      - uses: actions/checkout@v1

      - name: Run the server
        working-directory: .
        run: |
          docker-compose up --build -d

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - run: pip install pytest requests

      - name: Run system test
        working-directory: .
        run: pytest

      - name: Stop the server
        working-directory: .
        run: docker-compose down




